// <auto-generated />
using BasketballStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasketballStore.Migrations
{
    [DbContext(typeof(BasketballStoreContext))]
    [Migration("20240427142210_Los Angeles Lakers")]
    partial class LosAngelesLakers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasketballStore.Models.TeamName", b =>
                {
                    b.Property<int>("TeamNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamNameId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamNameId");

                    b.ToTable("TeamName");

                    b.HasData(
                        new
                        {
                            TeamNameId = 1,
                            Name = "Los Angeles Lakers"
                        },
                        new
                        {
                            TeamNameId = 2,
                            Name = "LA Clippers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
